# @package optimization
defaults:
  - _self_

seed: 0
loss_type: "flow"
loss_scale: 1.0
norm_type: "l1"
lr: 1e-4
weight_decay: 1e-5
num_steps: 1
sample_mode: "zero"
t_two_step: 0.9
discrete_dt: 0.01
grad_clip_norm: 10.0
ema_rate: 0.995
batch_size: 1024
dataloader_num_workers: 8
dataloader_persistent_workers: true
gradient_steps: 300000
warmup_ratio: 0.0
rampup_ratio: 0.5
min_value: 0.0
max_value: 1.0
model_path: null
interp_type: "linear"
device: "cuda"
disable_cudnn: false
use_compile: true
auto_resume: true
encoder_checkpoint_path: null
encoder_checkpoint_use_ema: true
freeze_encoder: false
use_future_embed_loss: false
future_embed_loss_mode: "direct"
future_embed_loss_weight: 0.1
future_state_loss_weight: 0.1
future_target_type: "state"
use_sigreg: false
sigreg_weight: 0.0
sigreg_knots: 17
sigreg_num_proj: 1024
