_target_: prometheus.nodes.robots.arx5.resolve_robot
id: x5_1
control_domain_id: 21
sensor_domain_id: 22

robot:
  state_publish_hz: 30
  action_space: abs_qpos
  gripper_width_m: 0.082
  gripper_open_readout: -3.4
  left_gripper_open_readout: -3.46056
  right_gripper_open_readout: -3.46475
  can:
    left: ${oc.env:ARX5_LEFT_CAN,can3}
    right: ${oc.env:ARX5_RIGHT_CAN,can1}

cameras:
  capture_hz: 30
  capture_width: 640
  capture_height: 480
  publish_hz: 30
  ir: false
  prepub_resize: 0.5
  camera_info: false
  serial_no:
    base_0: ${oc.env:BASE_CAMERA_SERIAL}
    left_wrist_0: ${oc.env:LEFT_WRIST_CAMERA_SERIAL}
    right_wrist_0: ${oc.env:RIGHT_WRIST_CAMERA_SERIAL}

tactile:
  publish_hz: 30
  prepub_resize: 1.0
  publish_flow: true
  publish_difference: false
  publish_raw: false
  require_gpu: true
  serial_no:
    left_wrist_0: "OG001262"
    left_wrist_1: "OG001263"
    right_wrist_0: "OG001267"
    right_wrist_1: "OG001266"
