# @package _global_
defaults:
  - /optimization: default
  - /network: chitransformer
  - /task: mug_mug_image
  - /log: default
  - _self_

mode: "train"

optimization:
  loss_type: "mip"
  seed: 2
  device: "cuda"
  disable_cudnn: true
  batch_size: 256
  use_compile: false
  dataloader_num_workers: 2
  dataloader_persistent_workers: false
  gradient_steps: 200000
  auto_resume: false
  future_target_type: "embedding"
  use_future_embed_loss: true
  future_embed_loss_mode: "direct"
  future_embed_loss_weight: 0.01

network:
  n_future_tokens: 1

task:
  future_state_enabled: true
  future_state_steps: 4
  future_target_type: "embedding"

log:
  log_dir: "logs/${task.env_name}_${task.env_type}_${task.obs_type}_future4_direct_fw${optimization.future_embed_loss_weight}_seed${optimization.seed}_run"
  exp_name: "${task.env_name}_${task.env_type}_${task.obs_type}_future4_direct_fw${optimization.future_embed_loss_weight}_seed${optimization.seed}"
  project: "jepa-policy"
  group: "libero_${task.env_name}"
  wandb_mode: "online"
  eval_freq: 10000
  eval_episodes: 40
  save_freq: 10000
