# @package _global_
defaults:
  - robocasa_mip_common
  - _self_

optimization:
  use_future_embed_loss: true
  future_embed_loss_mode: direct
  future_joint_mode: false
  future_state_loss_mode: ratio
  future_state_loss_ratio: 0.1
  future_state_loss_weight_min: 0.000001
  future_state_loss_weight_max: 0.1

network:
  n_future_tokens: 1

task:
  future_state_enabled: true
  future_state_steps: 4
  future_state_steps_list: [4]
  future_target_type: embedding

log:
  exp_name: "${task.env_name}_robocasa_image_future4_ratio010_seed${optimization.seed}"
  log_dir: "logs/robocasa/${log.exp_name}"
