# @package _global_
defaults:
  - robotwin_mip_common
  - _self_

optimization:
  use_future_embed_loss: false
  future_joint_mode: false

network:
  n_future_tokens: 0

task:
  future_state_enabled: false

log:
  exp_name: "${task.env_name}_robotwin_image_baseline_seed${optimization.seed}"
  log_dir: "logs/robotwin/${log.exp_name}"
