# @package task
defaults:
  - robomimic_base
  - _self_

env_name: "three_piece_assembly"
env_type: "mimicgen"
obs_type: "image"
dataset_repo: null
dataset_filename: null
dataset_path: "${oc.env:MIMICGEN_DATA_ROOT,datasets/mimicgen/core}/three_piece_assembly_d1/three_piece_assembly_d1.hdf5"
abs_action: false
max_episode_steps: 500
render_obs_key: "agentview_image"
horizon: 10
act_dim: 7
num_envs: 4

shape_meta:
  action:
    shape: [7]
  obs:
    agentview_image:
      shape: [3, 84, 84]
      type: rgb
    robot0_eye_in_hand_image:
      shape: [3, 84, 84]
      type: rgb
    robot0_eef_pos:
      shape: [3]
      type: low_dim
    robot0_eef_quat:
      shape: [4]
      type: low_dim
    robot0_gripper_qpos:
      shape: [2]
      type: low_dim
